# Generated by Django 3.0.1 on 2020-01-01 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authDemo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='type',
            field=models.IntegerField(choices=[(1, 'vip'), (2, 'vvip'), (3, 'General')], default=3),
        ),
    ]
